// <auto-generated />
namespace ClassroomBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updatedfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatedfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201912171146386_Updated fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
